"""
Top 50 F&O Stock Universe Definition.

Defines the curated liquid Top 50 Indian FnO stock symbols for Agent 1.5 Radar
and real-data backtesting benchmark.
"""

TOP_50_FNO = [
    "RELIANCE",
    "HDFCBANK",
    "ICICIBANK",
    "INFY",
    "ITC",
    "TCS",
    "LT",
    "BHARTIARTL",
    "AXISBANK",
    "SBIN",
    "KOTAKBANK",
    "BAJFINANCE",
    "HINDUNILVR",
    "M&M",
    "TATAMOTORS",
    "MARUTI",
    "SUNPHARMA",
    "NTPC",
    "TATASTEEL",
    "POWERGRID",
    "ULTRACEMCO",
    "ASIANPAINT",
    "COALINDIA",
    "TITAN",
    "ADANIENT",
    "ADANIPORTS",
    "BAJAJFINSV",
    "ONGC",
    "HCLTECH",
    "WIPRO",
    "DRREDDY",
    "GRASIM",
    "TECHM",
    "HINDALCO",
    "JSWSTEEL",
    "CIPLA",
    "TATACONSUM",
    "EICHERMOT",
    "APOLLOHOSP",
    "DIVISLAB",
    "BRITANNIA",
    "HEROMOTOCO",
    "SHRIRAMFIN",
    "BPCL",
    "LTIM",
    "TRENT",
    "INDUSINDBK",
    "BAJAJ-AUTO",
    "HDFCLIFE",
    "SBILIFE",
]
